name: controle_financeiro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1

  firebase_core: ^2.16.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  expense_repository:
    path: packages/expense_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/categorias/
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"